
document.addEventListener("DOMContentLoaded", () => {
  const toggle=document.querySelector(".menu-toggle"), nav=document.querySelector(".nav-links");
  if(toggle&&nav){toggle.addEventListener("click",()=>{const o=nav.classList.toggle("open");document.body.classList.toggle("menu-open",o);toggle.setAttribute("aria-expanded",String(o));toggle.textContent=o?"✕":"☰"});nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");document.body.classList.remove("menu-open");toggle.textContent="☰"}))}
  document.querySelectorAll(".faq-question").forEach(b=>b.addEventListener("click",()=>{const i=b.closest(".faq-item"),o=i.classList.toggle("open");b.setAttribute("aria-expanded",String(o))}));
  const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");obs.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(e=>obs.observe(e));
  window.dataLayer=window.dataLayer||[];
  document.querySelectorAll('a[href^="tel:"]').forEach(a=>a.addEventListener("click",()=>window.dataLayer.push({event:"phone_click",phone_number:a.getAttribute("href").replace("tel:","")})));
  document.querySelectorAll("[data-counter]").forEach(el=>{let done=false;const co=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting&&!done){done=true;const end=Number(el.dataset.counter),suffix=el.dataset.suffix||"";let cur=0;const step=Math.max(1,Math.ceil(end/45));const timer=setInterval(()=>{cur=Math.min(end,cur+step);el.textContent=cur+suffix;if(cur>=end)clearInterval(timer)},28);co.disconnect()}}));co.observe(el)});
  const zip=document.querySelector("#zip-check");if(zip){zip.addEventListener("submit",e=>{e.preventDefault();const v=zip.querySelector("input").value.trim();if(v){window.dataLayer.push({event:"coverage_check",zip_code:v});window.location.href="/contacto?zip="+encodeURIComponent(v)}})}
  const form=document.querySelector("#contact-form");if(form){const p=new URLSearchParams(location.search);if(p.get("zip")){const z=form.querySelector("#zip");if(z)z.value=p.get("zip")}form.addEventListener("submit",async e=>{e.preventDefault();const status=document.querySelector("#form-status"),btn=form.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent="Enviando…";status.textContent="";try{const data=Object.fromEntries(new FormData(form).entries());const r=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!r.ok)throw new Error();window.dataLayer.push({event:"lead_form_submit",lead_type:data.interest||"contact"});status.textContent="Gracias. Recibimos tu solicitud y te contactaremos durante el horario de atención.";status.style.color="#15803d";form.reset()}catch(err){status.innerHTML='No pudimos enviar el formulario. Llámanos al <a href="tel:+18183924132"><strong>818-392-4132</strong></a>.';status.style.color="#b91c1c"}finally{btn.disabled=false;btn.textContent="Solicitar llamada"}})}
});
